# Generated by Django 4.2.9 on 2024-03-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diaries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Diary_model',
        ),
    ]
